apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:236229348458:certificate/09ea55f3-c613-4de2-a399-0d4dc03f2653
  name: appleapi-service
  namespace: ingress-nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 6003
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6003
  selector:
    app: appleapi
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    clusterType: EKS
    owner: Arya Kumar
  labels:
    app: appleapi
  name: appleapi-deployment
  namespace: ingress-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appleapi
  template:
    metadata:
      labels:
        app: appleapi
    spec:
      containers:
      - image: 236229348458.dkr.ecr.us-east-1.amazonaws.com/appleapi:e6af9c7ee970290ba83630180e0333d5f5f1df3e
        imagePullPolicy: Always
        name: appleapi
        ports:
        - containerPort: 6003
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: appleapi-autoscaling
  namespace: ingress-nginx
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: appleapi-deployment
