# add ACCESS_KEY, SECRET_KEY, REPO_NAME into secret github actions.
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

name: upload image ECR

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.filter.outputs.workflows }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          workflows:
            - '.github/dev/**'
    # run only if 'workflows' files were changed
    - name: workflow tests
      if: steps.filter.outputs.workflows == 'true'
      run: echo "Workflow file"

    # run only if not 'workflows' files were changed
    - name: not workflow tests
      if: steps.filter.outputs.workflows != 'true'
      run: echo "NOT workflow file"
  build:
    name: Deploy
    runs-on: ubuntu-latest
    needs: paths-filter
    if: needs.paths-filter.outputs.output1 == 'true'

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
